### Invalid auth /token request
POST http://localhost:41360/auth/token HTTP/1.1
content-type: application/json

{
    "user": "test user",
    "password": "invalidpassword"
}

### Valid auth /token request
POST http://localhost:41360/auth/token HTTP/1.1
content-type: application/json

{
    "user": "test user",
    "password": "password"
}

### Valid auth /me check
GET http://localhost:41360/auth/me HTTP/1.1
X-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdCB1c2VyIiwiaWF0IjoxNjIwODM0Mzc0LCJleHAiOjE2MjA5MjA3NzR9.CNXt9d0O893Vna9DdcCPa2LdUYLyyV8qthjCB4JuYqM

### Valid document /me check
GET http://localhost:41360/doc/me HTTP/1.1
X-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdCB1c2VyIiwiaWF0IjoxNjIwODM0Mzc0LCJleHAiOjE2MjA5MjA3NzR9.CNXt9d0O893Vna9DdcCPa2LdUYLyyV8qthjCB4JuYqM


### Invalid document /me check
GET http://localhost:41360/doc/me HTTP/1.1


### Valid document /documents check
GET http://localhost:41360/doc/all HTTP/1.1
X-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdCB1c2VyIiwiaWF0IjoxNjIwODM0Mzc0LCJleHAiOjE2MjA5MjA3NzR9.CNXt9d0O893Vna9DdcCPa2LdUYLyyV8qthjCB4JuYqM

### Valid document /documents check
GET http://localhost:41360/doc/0 HTTP/1.1
X-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdCB1c2VyIiwiaWF0IjoxNjIwODM0Mzc0LCJleHAiOjE2MjA5MjA3NzR9.CNXt9d0O893Vna9DdcCPa2LdUYLyyV8qthjCB4JuYqM


### Valid document /documents check
PUT http://localhost:41360/doc/update/0 HTTP/1.1
X-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdCB1c2VyIiwiaWF0IjoxNjIwODM0Mzc0LCJleHAiOjE2MjA5MjA3NzR9.CNXt9d0O893Vna9DdcCPa2LdUYLyyV8qthjCB4JuYqM
Content-Type: text/plain

An h1 header
============

Paragraphs are separated by a blank line.

2nd paragraph. *Italic*, **bold**, and `monospace`. Itemized lists
look like:

  * this one
  * that one
  * the other one

Note that --- not considering the asterisk --- the actual text
content starts at 4-columns in.

> Block quotes are
> written like so.
>
> They can span multiple paragraphs,
> if you like.

Use 3 dashes for an em-dash. Use 2 dashes for ranges (ex., "it's all
in chapters 12--14"). Three dots ... will be converted to an ellipsis.
Unicode is supported. ☺

An h2 header
------------

Here's a numbered list:

 1. first item
 2. second item
 3. third item

Note again how the actual text starts at 4 columns in (4 characters
from the left side). Here's a code sample:
